In [ ]:
import torch

def slice_or_patch(old_tensor, indices, new_values = None):

    for i in range(len(indices)): 
        if isinstance(indices[i], slice):
            indices[i] = torch.arange(old_tensor.shape[i])
        if isinstance(indices[i], list): 
            indices[i] = torch.tensor(indices[i])

    index_grids = torch.meshgrid(*indices, indexing='ij')

    if new_values is None: 
        return old_tensor[index_grids]
    else: 
        #index_grids = [grid.expand(new_values.shape) for grid in index_grids]
        old_tensor[index_grids] = new_values
        return old_tensor


custom_tensor = torch.tensor([[[1.0,-2.0,5.0],[3.0,4.0,7.0],[-4.0,0.0,9.0]],[[3.0,-6.0,10.0],[-5.0,0.0,2.0],[15.0,1.0,26.0]],[[34.0,-21.0,8.0],[22.0,90.0,-89.0],[23.0,74.0,81.0]]])
perm = torch.randperm(custom_tensor.size(0))
print(custom_tensor.size(0))
print(custom_tensor[perm])
print(torch.mean(custom_tensor,dim=(0,1),keepdim=True).shape)
rows = [0,1]
cols = [1,2]

print(torch.mean(custom_tensor,dim= 0, keepdim = True).expand([3] + (custom_tensor.dim() - 1)*[-1]))

print(slice_or_patch(custom_tensor,[rows,cols,slice(None)],slice_or_patch(custom_tensor,[rows,cols,slice(None)])*3))

new_values = slice_or_patch(custom_tensor,[slice(None),[1,2],[0,1]])*3

new_tensor = slice_or_patch(custom_tensor,[slice(None),[1,2],[0,1]],new_values)

#print(new_tensor)



3
tensor([[[  1.,  -2.,   5.],
         [  3.,   4.,   7.],
         [ -4.,   0.,   9.]],

        [[  3.,  -6.,  10.],
         [ -5.,   0.,   2.],
         [ 15.,   1.,  26.]],

        [[ 34., -21.,   8.],
         [ 22.,  90., -89.],
         [ 23.,  74.,  81.]]])
torch.Size([1, 1, 3])
tensor([[[ 12.6667,  -9.6667,   7.6667],
         [  6.6667,  31.3333, -26.6667],
         [ 11.3333,  25.0000,  38.6667]],

        [[ 12.6667,  -9.6667,   7.6667],
         [  6.6667,  31.3333, -26.6667],
         [ 11.3333,  25.0000,  38.6667]],

        [[ 12.6667,  -9.6667,   7.6667],
         [  6.6667,  31.3333, -26.6667],
         [ 11.3333,  25.0000,  38.6667]]])
tensor([[[  1.,  -2.,   5.],
         [  9.,  12.,  21.],
         [-12.,   0.,  27.]],

        [[  3.,  -6.,  10.],
         [-15.,   0.,   6.],
         [ 45.,   3.,  78.]],

        [[ 34., -21.,   8.],
         [ 22.,  90., -89.],
         [ 23.,  74.,  81.]]])


In [3]:
import numpy as np

new_array = np.zeros((1,2),float)
new_array[0,0] = 5
new_array[0,1] = 6
print(new_array)

[[5. 6.]]


In [38]:
test_dict = {(i,"hei"): torch.tensor([1,4]) for i in range(5)}
print(test_dict)
print(torch.stack(list(test_dict.values())).shape)

test_tensor = torch.tensor([[1,3,221,45,67,89],[4,5,89,90,93,74],[6,7,56,45,47,645],[8,9,76,34,2874,767],[0,-1,10,13,64,3748],[9,34,57,15,7826,874446]])
print(test_tensor.shape)

print(torch.stack(torch.chunk(test_tensor, 2, dim=-1)).shape)


{(0, 'hei'): tensor([1, 4]), (1, 'hei'): tensor([1, 4]), (2, 'hei'): tensor([1, 4]), (3, 'hei'): tensor([1, 4]), (4, 'hei'): tensor([1, 4])}
torch.Size([5, 2])
torch.Size([6, 6])
torch.Size([2, 6, 3])


In [40]:
sender_node = {(1,"attn"): 5}
receiver_node = {(5,"MLP"): 3}

attn_head_nodes = {(i,"attn"): list(range(12)) for i in range(6)}

print(list(attn_head_nodes.items()))

print(dict(list(attn_head_nodes.items())[list(sender_node.keys())[0][0] + 1:list(receiver_node.keys())[0][0]]))

[((0, 'attn'), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]), ((1, 'attn'), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]), ((2, 'attn'), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]), ((3, 'attn'), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]), ((4, 'attn'), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]), ((5, 'attn'), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])]
{(2, 'attn'): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], (3, 'attn'): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], (4, 'attn'): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]}


In [45]:
import torch
test_dict = {"hei": torch.tensor([0,1]), "på": torch.tensor([2,3]), "deg": torch.tensor([4,5])}
new_dict = {}

for key, value in test_dict.items(): 
    new_dict[key] = "halla på deg"
print(new_dict)
print(torch.tensor(list(test_dict.values())))
print(torch.tensor(list(test_dict.values())).shape)

{'hei': 'halla på deg', 'på': 'halla på deg', 'deg': 'halla på deg'}


TypeError: only integer tensors of a single element can be converted to an index